<h3>HOMEPAGE</h3>
<hr />
<span style="padding-left: 30px;"><input type="text" name="searchClass" value="Search class name" size="30px" style="vertical-align: middle; color: gray;  " /></span> 
<span style="padding-left: 150px;"><input type="button" name="addCourse" onclick="location.href='<?php echo $this->baseUrl(); ?>/course/add'" value="Add Course" id="addCourse" /></span>
<span style="padding-left: 200px;"><input type="button" name="addClass" onclick="location.href='<?php echo $this->baseUrl(); ?>/class/add'" value="Add Class" id="addClass" /></span>

<br />
<h5 style="padding-left: 40px;">List</h5>


<div class="divTable">
    <div class="headRow">
        <div  class="divCell"> <img src="img/increase.png" />  Name</div>
        <div  class="divCell"> <img src="img/increase.png" /> Regis date</div>
        <div  class="divCell"> <img src="img/increase.png" /> Members</div>
        <div  class="divCell"> <img src="img/increase.png" /> Course</div>
        <div  class="divCell"> <img src="img/increase.png" /> % day</div>
        <div  class="divCell"> <img src="img/increase.png" /> % material</div>
        <div  class="divCell">  Edit</div>
    </div>
     
    <div class="divRow">
        <div class="divCell">001</div>
        <div class="divCell">002</div>
        <div class="divCell">003</div>
        <div class="divCell">003</div>
        <div class="divCell">003</div>
        <div class="divCell">003</div>
        <div class="divCell">003</div>
    </div>
    
    <div class="divRow">
        <div class="divCell">xxx</div>
        <div class="divCell">yyy</div>
        <div class="divCell">www</div>
        <div class="divCell">www</div>
        <div class="divCell">www</div>
        <div class="divCell">www</div>
        <div class="divCell">www</div>
   </div>
   
    <div class="divRow">
        <div class="divCell">ttt</div>
        <div class="divCell">uuu</div>
        <div class="divCell">Mkkk</div>
        <div class="divCell">Mkkk</div>
        <div class="divCell">Mkkk</div>
        <div class="divCell">Mkkk</div>
        <div class="divCell">Mkkk</div>
   </div>
</div>